### ISSUE TITLE
[Bug]Bug when openning my.epitech

### ISSUE THREAD

**Issue by BastienBoymond** [alwyn974/MyEpitechExt#1]
When we open my epitech the pourcent appear but 3 time we have something like that
![bug](https://user-images.githubusercontent.com/71839723/136016172-89bfe87a-085b-46bf-b761-9b5e402e6e18.png)
how to do its :
Open my.epitech
go somewhere with projet that good grade

**Comment by alwyn974** [comment]
Can you send me the console logs?
You need to activate the **Verbose** level

For the moment a refresh of the page should fix it

*Aussi on pourrait directement parler français x)*

**Comment by BastienBoymond** [comment]
Voila tout les log 
Apres actuellement je suis au boulot mais quand je suis chez moi je peux regarder et te faire une pull request

[debug.log](https://github.com/alwyn974/MyEpitechExt/files/7285987/debug.log)

**Comment by alwyn974** [comment]
Merci je vais voir ça
A vrai dire je sais déjà d'où ça vient mais c'était déjà censé être réglé ce bug x)

**Comment by alwyn974** [comment]
Alors j'ai regardé et j'ai trouvé plus précisément d'où vient le bug.
C'est quand on change d'année (2021 => 2020)
- Il y a au moins deux barres 
- Les timers sont cassé aussi

Je fixerais ça ce weekend

**Comment by BastienBoymond** [comment]
Tu as un peu trop bien regler le truc maintenant au lieu de s'afficher 3 fois ça s'affiche 0 quand tu passe de 2021 a 2020

**Comment by alwyn974** [comment]
Tu pourrais renvoyer les logs ?
Je vais voir ça en rentrant ce soir

**Comment by BastienBoymond** [comment]
log vide

**Comment by alwyn974** [comment]
Ah c'est embêtant ça, même sur la page 2021 il n'y a rien ?
Bon au pire je ferais sans

**Comment by alwyn974** [comment]
D'après ce que j'ai vu ça arrive quand on passe de https://my.epitech.eu/ => https://my.epitech.eu/#y/2021 (redirection auto)

Sauf que moi la barre apparait quand même (Chrome, Firefox) mais sur Kiwi Browser j'ai le bug (bon au final Kiwi Browser c'est encore autre chose)

**Comment by alwyn974** [comment]
Il me fautdrait la version du navigateur + le type (chrome, firefox etc)

Aussi il me faudrait les logs "background" :
- Chrome => chrome://extensions (activer le mode développeur avant)
![chrome debug](https://i.imgur.com/IGfjX5n.png)
- about:debugging#/runtime/this-firefox
![firefox debug](https://i.imgur.com/06sJX7H.png)

**Comment by BastienBoymond** [comment]
[MyEpitechExt] https://my.epitech.eu/index.html#2020/all/all intercepted, send refresh message

**Comment by BastienBoymond** [comment]
Chrome Lastest version

**Comment by alwyn974** [comment]
> https://my.epitech.eu/index.html#2020/all/all

Oh mais celle url là n'est pas valide normalement 🤔 (*c'est censé être l'ancien format*)

Essaye en allant sur https://my.epitech.eu/ (en étant déjà connecté), et ensuite d'aller sur l'année 2020 voir si la barre s'affiche

**Comment by BastienBoymond** [comment]
ça s'affiche bien

**Comment by alwyn974** [comment]
C'est bizarre ce bug, je close l'issue (*vu que c'est assez spécial pour avoir ce bug*) si jamais tu l'as encore réouvre là
